

library(tidyverse)

input <- read_csv("C:/Users/afehir/Documents/Projects/Toronto/GPR/before_dictinct_GPR.csv")
  
distinct <- input %>% 
  group_by(IDLocator, IDSession, BeginDistanceStamp, EndDistanceStamp) %>% 
  mutate(BeginChainage = first(BeginChainage),
         EndChainage = first(EndChainage),
         AC_DEF_H = first(AC_DEF_H),
         AC_DEF_L = first(AC_DEF_L),
         AC_DEF_M = first(AC_DEF_M),
         AC_FLU_H = first(AC_FLU_H),
         AC_FLU_L = first(AC_FLU_L),
         AC_FLU_M = first(AC_FLU_M),
         AC_POTHOLE = first(AC_POTHOLE),
         AC_RAV_H = first(AC_RAV_H),
         AC_RAV_L = first(AC_RAV_L),
         AC_RAV_M = first(AC_RAV_M),
         AC_RIP_H = first(AC_RIP_H),
         AC_RIP_L = first(AC_RIP_L),
         AC_RIP_M = first(AC_RIP_M),
         ACCPATCH_H = first(ACCPATCH_H),
         ACCPATCH_L = first(ACCPATCH_L),
         ACCPATCH_M = first(ACCPATCH_M),
         ALLIG_H = first(ALLIG_H),
         ALLIG_L = first(ALLIG_L),
         ALLIG_M = first(ALLIG_M),
         BLOCK_H = first(BLOCK_H),
         BLOCK_L = first(BLOCK_L),
         BLOCK_M = first(BLOCK_M),
         BRGE = first(BRGE),
         CHAINBEG = first(CHAINBEG),
         CHAINEND = first(CHAINEND),
         CONSTN = first(CONSTN),
         CORN_H = first(CORN_H),
         CORN_L = first(CORN_L),
         CORN_M = first(CORN_M),
         CROWN = first(CROWN),
         DATADATE = first(DATADATE),
         DCRACK_H = first(DCRACK_H),
         DCRACK_L = first(DCRACK_L),
         DCRACK_M = first(DCRACK_M),
         DEVN = first(DEVN),
         DIR = first(DIR),
         DIVIDED = first(DIVIDED),
         EDGE_H = first(EDGE_H),
         EDGE_L = first(EDGE_L),
         EDGE_M = first(EDGE_M),
         ELEVATION = first(ELEVATION),
         FAULT_H = first(FAULT_H),
         FAULT_L = first(FAULT_L),
         FAULT_M = first(FAULT_M),
         FClass = first(FClass),
         FILENAME = first(FILENAME),
         FKEY = first(FKEY),
         FROM_STREET = first(FROM_STREET),
         IRI_AVG = first(IRI_AVG),
         IRI_FLAG = first(IRI_FLAG),
         JC_CAL_H = first(JC_CAL_H),
         JC_CAL_L = first(JC_CAL_L),
         JC_CAL_M = first(JC_CAL_M),
         JC_DIS_H = first(JC_DIS_H),
         JC_DIS_L = first(JC_DIS_L),
         JC_DIS_M = first(JC_DIS_M),
         JC_POL_H = first(JC_POL_H),
         JC_POL_L = first(JC_POL_L),
         JC_POL_M = first(JC_POL_M),
         JC_RAV_H = first(JC_RAV_H),
         JC_RAV_L = first(JC_RAV_L),
         JC_RAV_M = first(JC_RAV_M),
         JC_SCAL_H = first(JC_SCAL_H),
         JC_SCAL_L = first(JC_SCAL_L),
         JC_SCAL_M = first(JC_SCAL_M),
         JOINTSEAL_H = first(JOINTSEAL_H),
         JOINTSEAL_L = first(JOINTSEAL_L),
         JOINTSEAL_M = first(JOINTSEAL_M),
         JOINTSPALL_H = first(JOINTSPALL_H),
         JOINTSPALL_L = first(JOINTSPALL_L),
         JOINTSPALL_M = first(JOINTSPALL_M),
         LANES = first(LANES),
         LANEWIDTH = first(LANEWIDTH),
         LATITUDE = first(LATITUDE),
         LINEAR_H = first(LINEAR_H),
         LINEAR_L = first(LINEAR_L),
         LINEAR_M = first(LINEAR_M),
         LIRI = first(LIRI),
         LONG_H = first(LONG_H),
         LONG_L = first(LONG_L),
         LONG_M = first(LONG_M),
         LONGITUDE = first(LONGITUDE),
         LRUT = first(LRUT),
         ONEWAY = first(ONEWAY),
         PAVETYPE = first(PAVETYPE),
         PC_POTHOLE = first(PC_POTHOLE),
         PC_TRANS_H = first(PC_TRANS_H),
         PC_TRANS_L = first(PC_TRANS_L),
         PC_TRANS_M = first(PC_TRANS_M),
         PCCPATCH_H = first(PCCPATCH_H),
         PCCPATCH_L = first(PCCPATCH_L),
         PCCPATCH_M = first(PCCPATCH_M),
         PQI = first(PQI),
         RIRI = first(RIRI),
         RRUT = first(RRUT),
         RRXING = first(RRXING),
         RUT_AVG = first(RUT_AVG),
         SECTION = first(SECTION),
         SPEED = first(SPEED),
         STATN = first(STATN),
         TO_Area = first(TO_Area),
         TO_Length = first(TO_Length),
         TO_Ptype = first(TO_Ptype),
         TO_STREET = first(TO_STREET),
         TO_Width = first(TO_Width),
         TRANS_H = first(TRANS_H),
         TRANS_L = first(TRANS_L),
         TRANS_M = first(TRANS_M),
         XFALL = first(XFALL),
         Level = first(Level),
         Status = first(Status),
         Year = first(Year),
         ID = first(ID),
         State = first(State),
         QCStatus = first(QCStatus),
         Comment = first(Comment),
         Layer1_Material = first(Layer1_Material),
         Layer1_Depth = first(Layer1_Depth),
         Layer1_Thickness = first(Layer1_Thickness),
         Layer1_2WayTime = first(Layer1_2WayTime),
         Layer1_DielectricConstant = first(Layer1_DielectricConstant),
         Layer2_Material = first(Layer2_Material),
         Layer2_Depth = first(Layer2_Depth),
         Layer2_Thickness = first(Layer2_Thickness),
         Layer2_2WayTime = first(Layer2_2WayTime),
         Layer2_DielectricConstant = first(Layer2_DielectricConstant),
         Layer3_Depth = first(Layer3_Depth),
         Layer3_Material = first(Layer3_Material),
         Layer3_Thickness = first(Layer3_Thickness),
         Layer3_2WayTime = first(Layer3_2WayTime),
         Layer3_DielectricConstant = first(Layer3_DielectricConstant),
         Layer4_Depth = first(Layer4_Depth),
         Layer4_Material = first(Layer4_Material),
         Layer4_Thickness = first(Layer4_Thickness),
         Layer4_2WayTime = first(Layer4_2WayTime),
         Layer4_DielectricConstant = first(Layer4_DielectricConstant),
         SourceFilename = first(SourceFilename)) %>% 
  distinct(IDLocator,  IDSession,  BeginDistanceStamp,  EndDistanceStamp,  BeginChainage,  EndChainage,  
           AC_DEF_H,  AC_DEF_L,  AC_DEF_M,  AC_FLU_H,  AC_FLU_L,  AC_FLU_M,  AC_POTHOLE,  AC_RAV_H,  
           AC_RAV_L,  AC_RAV_M,  AC_RIP_H,  AC_RIP_L,  AC_RIP_M,  ACCPATCH_H,  ACCPATCH_L,  ACCPATCH_M,  
           ALLIG_H,  ALLIG_L,  ALLIG_M,  BLOCK_H,  BLOCK_L,  BLOCK_M,  BRGE,  CHAINBEG,  CHAINEND,  
           CONSTN,  CORN_H,  CORN_L,  CORN_M,  CROWN,  DATADATE,  DCRACK_H,  DCRACK_L,  DCRACK_M,  
           DEVN,  DIR,  DIVIDED,  EDGE_H,  EDGE_L,  EDGE_M,  ELEVATION,  FAULT_H,  FAULT_L,  FAULT_M,  
           FClass,  FILENAME,  FKEY,  FROM_STREET,  IRI_AVG,  IRI_FLAG,  JC_CAL_H,  JC_CAL_L,  JC_CAL_M, 
           JC_DIS_H,  JC_DIS_L,  JC_DIS_M,  JC_POL_H,  JC_POL_L,  JC_POL_M,  JC_RAV_H,  JC_RAV_L,  
           JC_RAV_M,  JC_SCAL_H,  JC_SCAL_L,  JC_SCAL_M,  JOINTSEAL_H,  JOINTSEAL_L,  JOINTSEAL_M, 
           JOINTSPALL_H,  JOINTSPALL_L,  JOINTSPALL_M,  LANES,  LANEWIDTH,  LATITUDE,  LINEAR_H, 
           LINEAR_L,  LINEAR_M,  LIRI,  LONG_H,  LONG_L,  LONG_M,  LONGITUDE,  LRUT,  ONEWAY,  PAVETYPE, 
           PC_POTHOLE,  PC_TRANS_H,  PC_TRANS_L,  PC_TRANS_M,  PCCPATCH_H,  PCCPATCH_L,  PCCPATCH_M,  
           PQI,  RIRI,  RRUT,  RRXING,  RUT_AVG,  SECTION,  SPEED,  STATN,  TO_Area,  TO_Length,  
           TO_Ptype,  TO_STREET,  TO_Width,  TRANS_H,  TRANS_L,  TRANS_M,  XFALL,  Level,  Status, 
           Year,  ID,  State,  QCStatus,  Comment,  Layer1_Material,  Layer1_Depth,  Layer1_Thickness, 
           Layer1_2WayTime,  Layer1_DielectricConstant,  Layer2_Material,  Layer2_Depth,  Layer2_Thickness, 
           Layer2_2WayTime,  Layer2_DielectricConstant,  Layer3_Depth,  Layer3_Material,  Layer3_Thickness, 
           Layer3_2WayTime,  Layer3_DielectricConstant,  Layer4_Depth,  Layer4_Material,  Layer4_Thickness, 
           Layer4_2WayTime,  Layer4_DielectricConstant,  SourceFilename) %>% 
  filter(Level == 10)

write_csv(distinct, "C:/Users/afehir/Documents/Projects/Toronto/GPR/after_dictinct_GPR.csv")

# 
############## This creates the x = first(x) used by the mutate ####################################

# b <- c()
# for (i in names(input)){
#   b <- append(b, str_c(i, " = ", "first(", i, "),"))
# }
# 
# cat(b, sep = "\n")
 
 
############### This creates the  string of the list of names(input) with commas separating them ################

# c <- c()
# for (i in names(input)){
#   c <- append(c, str_c(i, ", "))
# }
# 
# cat(c, sep = " ")